### ISSUE TITLE
Song can't be escaped

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#11]
The feedback from anonymous on November 8th 2015 was:

> While the video is playing on phone you cannot exit it until the song is over
> 1. Open a musare.com room
> 2. Press the play button to get the song up
> 3. It will go in fullscreen.
> 4. Press done. to exit fullscreen. It wont close

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/73627)

**Comment by KrisVos130** [comment]
Instructions are not clear for me. What does 'it' refer to when saying 'cannot exit it'? Does it mean can you not exit the page, browser, go to the dashboard or something else?

**Comment by ghost** [comment]
Not sure what this user are trying to tell, but I think when you have pressed the start button on the song, then you try to end the song by pressing done it keeps popping up

**Comment by AkiraLaine** [comment]
I'm not sure what the issue means, but there haven't been any other users w/ this issue. I'm closing this for now.

**Comment by ghost** [comment]
I can confirm this issue is still relevant.

**Comment by KrisVos130** [comment]
Needs better steps to reproduce.

**Comment by AkiraLaine** [comment]
If I click "play" on and iPad it doesn't go full screen. Also, there is no way to "disable" full screen mode as far as I know.

**Comment by ghost** [comment]
_wops_
