### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#15]
The feedback from anonymous on November 9th 2015 was:

> 1. The songs tend to cut out prematurely, and it breaks the flow. 
> 2. The chat window should always be scrolled to the bottom upon loading, IRC-style.
> 3. The feedback button should be moved somewhere that doesn't block an interactive area (eg, the chat input)  of  the site. The bottom-left corner is looking pretty good right now.

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/73851)

**Comment by ghost** [comment]
1. We are looking into the issue
2. Working on it now
3. done

**Comment by ghost** [comment]
1. Working on a fix
2. Done
3. Done

**Comment by AkiraLaine** [comment]
For 1, I have made the necessary improvements. Hopefully songs don't end too early anymore.
