### ISSUE TITLE
iPad issue 

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#18]
The feedback from anonymous on November 10th 2015 was:

> Music is not playing on my IPad plz fix

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/74282)

**Comment by ghost** [comment]
Cant reproduce. Please reopen and give a more detailed response how to reproduce this.

**Comment by AkiraLaine** [comment]
@johand199 Music won't autoplay on mobile/tablets. We are trying to find a way to make it work

**Comment by KrisVos130** [comment]
This is not an issue on Musare. This is something mobile devices automatically do. Mobile devices disable autoplaying of songs. They do this so mobile devices don't use lots of data. We will however make an Android and iOS app of Musare in the future.
