### ISSUE TITLE
Chrome update workaround suggestion

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#19]
The feedback from anonymous on November 12th 2015 was:

> Hey guys, Cameron here (Wesley/Septimus's bro). I see you guys are having an issue with the new release of Chrome not playing media when the tab is inactive. Wesley won't stop complaining about it so I suggested that you guys just throw it into an Electron or NW.js app (that should probably fix the issue you guys are having). I think it would be cool to have a downloadable app either way. Anyways there's my two cents. Thanks :D. Cool music app :)

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/74686)

**Comment by KrisVos130** [comment]
We have made an electron version of Musare, and that indeed fixes it, yet we will still need to either find a workaround for the Chrome thing or wait until Chrome makes an option to disable this 'feature'.
