### ISSUE TITLE
Christmas room

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#23]
The feedback from anonymous on November 14th 2015 was:

> Hey guys this is random but it would be cool to have a Christmas room with Christmas songs playing, when it gets near Christmas or something. :)

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/75531)

**Comment by ghost** [comment]
+1

**Comment by KrisVos130** [comment]
+1

**Comment by arvind-iyer** [comment]
With a red and white theme instead of the green too!
