### ISSUE TITLE
Feedback by Cosmin Cebuc

### ISSUE THREAD

**Issue by AkiraLaine** [Musare/MusareMeteor#25]
Hi there,

First of all congrats on your project.
1. I think a F.A.Q. section would be welcomed since I guess many users will ask the same question over and over again: (ex: How do I add a song?; Can I skip a song?; I added a song but I can't find it in the Playlist)
2. Some people have slow internet connections, maby you should put a button where people can turn off the video and only get the audio to save bandwith ('dunno if it is possible)

I'll get back to you if I think of anything else :)

Kind regards,
Cosmin Cebuc

**Comment by ghost** [comment]
1. I'll start on the FAQ section ASAP
2. We got the hide button there, but there is no way to block the video without breaking the terms of youtube.

**Comment by KrisVos130** [comment]
For point 2, we can't disable video's, but we can turn the quality to the worst quality available.

**Comment by KrisVos130** [comment]
Quick update: We added the FAQ.

**Comment by AkiraLaine** [comment]
Closing this as FAQ has been added and we can't actually "turn off" the video.
