### ISSUE TITLE
Artist name + Song Title keeps changing

### ISSUE THREAD

**Issue by ghost** [Musare/MusareMeteor#26]
The feedback from anonymous on November 22nd 2015 was:

> Hello again, 
> 
> I have a gaming stream on twitch.tv.
> 
> I use your website for music on the stream. I also use "window capture" to capture a portion of a window showing the Artist and Title of the song from your website.
> 
> The problem is, the size (height) of the Artist name + Song Title keeps changing depending if they are longer or shorter artist names and titles.
> 
> Can you make it so that the height/width in wich they are displayed are fixed sizes?
> 
> Only do it if you think it benefits the site, not for me :) ...
> 
> Just saying, maybe more streamers will use the site that way. thanks

View it on [Doorbell](https://doorbell.io/applications/2408/feedback/78028)

**Comment by AkiraLaine** [comment]
This is awesome that streamers use Musare! 
I'd love to know who the Twitch streamer is :stuck_out_tongue_winking_eye:

**Comment by ghost** [comment]
Will be fixed with the new site when that goes live.
