### ISSUE TITLE
Ability to jump between the three chat-rooms 

### ISSUE THREAD

**Issue by arvind-iyer** [Musare/MusareMeteor#31]

**Comment by ghost** [comment]
:-1: Sorry i feel like it should be per to per room. to keep it simple and not confusing. people also might think they are in a other chat room

**Comment by KrisVos130** [comment]
Maybe not all three chatrooms, but we might be able to use a global chatroom for all rooms as a 3rd tab next to the per room chat.

**Comment by arvind-iyer** [comment]
Fair enough, just thought it might be cool right now because there aren't too many people, I guess if more people use the site, it makes sense it keep it split

**Comment by ghost** [comment]
Voting period done. As we have talked about it and confirms this is not an idea we will add. ill close this
