### ISSUE TITLE
Admin section preview crashes web browser.

### ISSUE THREAD

**Issue by Septimus** [Musare/MusareMeteor#34]
Tested with Firefox.
Number of tries: 5

When trying to preview a song inside of the admin section and hit play Firefox crashes. Not a super important issue as it isn't user facing but I will look into it if nobody else does quickly.

**Comment by KrisVos130** [comment]
Can't reproduce on the Firefox Developer edition.

**Comment by Septimus** [comment]
Huh. Maybe it is Firefox Mac specific? I'll continue to do some research.

**Comment by KrisVos130** [comment]
Fixed in 73ce783.
