### ISSUE TITLE
Getting routing error

### ISSUE THREAD

**Issue by kurzninja** [Musare/MusareMeteor#35]
I'm getting the following routing error in the console when I try to join a room:

```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
```

**Comment by AkiraLaine** [comment]
Does this prevent you from entering the room or listening to music?

**Comment by AkiraLaine** [comment]
Does this prevent you from entering the room or listening to music?

**Comment by kurzninja** [comment]
Yes: my apologies. I also sent a report on the feedback tab on the site. Clicking a genre brings up a brief loading circle as if it's going to load the room then simply redirects me back to the genre selection screen.

**Comment by AkiraLaine** [comment]
Weird. I remember seing this error, but not that it prevented me from enetring the room. We will look into this.

**Comment by KrisVos130** [comment]
Fixed this issue. And the error `Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?` had nothing to do with this error, thanks for telling us though.
